config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root "articles#index"
  #get "/articles", to: "articles#index"
  #to show all article list
  #get "/articles/:id", to: "articles#show"
  #to show single article list
  # For details on the DSL available within this 
  #file, see https://guides.rubyonrails.org/routing.html
  resources :articles do
    resources :comments
  end

  # root to: redirect('/admin')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

	# include Visible
	
	has_many :comments, dependent: :destroy

	validates :title, presence: true
	validates :body, presence: { message: "Body is mandatory"}, length: { minimum: 10}
	# VALID_STATUSES = ['public', 'private', 'archived']

 #  validates :status, inclusion: { in: VALID_STATUSES }

 #  def archived?
 #    status == 'archived'
 #  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  # include Visible
  belongs_to :article

  # VALID_STATUSES = ['public', 'private', 'archived']

  # validates :status, inclusion: { in: VALID_STATUSES }

  # def archived?
  #   status == 'archived'
  # end
end

app/models/concerns/visible.rb
# module Visible

#   extend ActiveSupport::Concern

#   VALID_STATUSES = ['public', 'private', 'archived']

#   included do
#     validates :status, inclusion: { in: VALID_STATUSES }
#     #scope :archived, -> { where('status != ?', nil) }
#   end

#   class_methods do
#     def public_count
#       where(status: 'public').count
#     end
#   end

#   def archived?
#     status == 'archived'
#   end
# end

app/models/product.rb
class Product < ApplicationRecord
	# self.table_name = "my_products"
	# self.primary_key = "product_id"
	validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  

http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  #we will pass the para in address bar that
  # that will come in the parameter place
   def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    
    if @article.save
      redirect_to @article
    else
      flash[:danger] = 'Something went wrong.'
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :status)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	  

 http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

  def index
    @comment = Comment.all
  end

  def show
    @comment = Comment.find_by(id: params[:id])
  end

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
      @article = Article.find(params[:article_id])
      @comment = @article.comments.find(params[:id])
      @comment.destroy
      redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

<div>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
</div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>
<!-- <%= form_with model: @article do |form| %> 
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% @article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
-->

app/views/articles/index.html.erb
 <h1>Articles and Comments and Concerns</h1>
<!-- <p>Find me in app/views/articles/index.html.erb</p> -->
<h1>Hello, Rails!</h1>
<h1>Articles</h1>
<!-- Our blog has <%#= Article.public_count %> articles and counting! -->
<ul>
  <% @articles.each do |article| %>
    <% if article.present? %>
      <li>
        <%=article.title %>
      </li>
    <% else %>
      <%= "Article not found" %>
    <% end %>
  <% end %>
</ul>


<h1>Articles</h1>
<ul>
  <% @articles.each do |article| %>
  <%# unless article.archived? %>
    <li>
      <%= link_to article.title, article %>
    </li>
    <%# end %>
  <% end %>
</ul>
<%= link_to "New Article", new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%=@article.title %></h1>
BODY
<p><%=@article.body %></p>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
  <li><%= button_to "Destroy", article_path(@article),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>  
         <li><%= link_to "Back", articles_path %></li>         
</ul>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<!-- <p>
  <strong>Commenter:</strong>
  <%#= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%#= comment.body %>
</p>

<p>
  <strong>status:</strong>
  <%#= comment.status %>
</p>


 -->
<table>
  <tr>
    <%# unless comment.archived? %>
    <th> Commenter</th>
    <tr>
      <td><%= comment.commenter %></td>
      <td><%= link_to 'Show', article_comment_path(article_id: comment.article.id, id: comment.id) %>
        <%# end %></td>
    </tr>
  </table>
 

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  
<p>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
</p>
  <p>
    <%= form.submit %>
  </p>


<% end %>

app/views/comments/comment_index.html.erb
<h1>Comments</h1>
Our blog has <%= comment.public_count %> articles and counting!
<ul>
  <% @comments.each do |comment| %>
    <li>
      <%= comment.commenter %>
    </li>
  <% end %>
</ul>

<ul>
  <% @comments.each do |comment| %>
  <% unless comment.archived? %>
    <li>
      <%= link_to comment.commenter, comment %>
    </li>
    <% end %>
  <% end %>
</ul>
<%= link_to "comment_show", article_comment %>

app/views/comments/show.html.erb
<table>
  <tr>
    <th>commenter</th>
    <th>comment</th>
    <th>status</th>

  </tr>
  <tr>
    <td><%= @comment.commenter %></td>  
    <td><%= @comment.body %></td>
    <td><%= @comment.status %></td>
    </tr>
    <td><%= link_to 'Destroy Comment', [@comment.article, @comment],
              method: :delete,
              data: { confirm: "Are you sure?" } %></td>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>